schema: schema.graphql
documents: '**/*.graphql'
extensions:
  endpoints:
    "Gatsby GraphQL Endpoint":
      url: 'http://localhost:8000/___graphql'
      headers:
        "user-agent": "JS GraphQL"
      introspect: false
